spring:
  application:
    name: governancecore

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/governancecore}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: false
    

# application.yaml or application.yml is where you configure how your app runs.

# application.yaml = Runtime configuration (when the app is running)

# This file answers questions like:

# What database should I connect to?

# What username/password should I use?

# Should Flyway run migrations on startup?

# What port should the server run on?

# Logging level? Security settings? Profiles?

# application.yaml configures how those dependencies behave at runtime.